name: "plan_model"
platform: "tensorrt_plan"
max_batch_size: 1
input [
    {
        name: "input.0"
        data_type: TYPE_FP32
        dims: [3, 224, 224]
    }
]
output [
    {
        name: "identity_output.0"
        data_type: TYPE_FP32
        dims: [30]
    }
]

